"""Professional AI Chat Service for natural language procurement analysis."""

from __future__ import annotations
import json
import re
from decimal import Decimal
from typing import Any, List, Dict
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession
from groq import AsyncGroq
from core.logger import get_logger
from backend.core.config import settings

logger = get_logger("services.chat")

class AuditChatService:
    """Service to handle natural language queries over the procurement database using Groq."""

    ALLOWED_SQL_COLUMNS = {
        "departments": {"id", "name"},
        "fornecedores": {"id", "razao_social", "nome_fantasia"},
        "produtos": {"ean", "nome_limpo", "marca", "categoria", "unidade"},
        "notas_fiscais": {
            "id",
            "fornecedor_id",
            "department_id",
            "numero_nota",
            "data_emissao",
            "valor_total",
            "status",
        },
        "itens_notas_fiscais": {
            "nota_fiscal_id",
            "ean",
            "quantidade",
            "valor_unitario",
            "valor_total",
        },
        "historico_precos": {
            "ean",
            "data_compra",
            "preco_unitario",
            "fornecedor_id",
        },
    }

    SCHEMA_CONTEXT = """
    Tabelas disponíveis para consulta:
    
    1. 'departments': id, name.
    2. 'fornecedores': id, razao_social, nome_fantasia.
    3. 'produtos': ean, nome_limpo, marca, categoria, unidade.
    4. 'notas_fiscais': id, fornecedor_id, department_id, numero_nota, data_emissao, valor_total, status.
    5. 'itens_notas_fiscais': nota_fiscal_id, ean, quantidade, valor_unitario, valor_total.
    6. 'historico_precos': ean, data_compra, preco_unitario, fornecedor_id.

    Dados fiscais ou pessoais sensíveis não estão disponíveis para o chat.
    """

    def __init__(self, db: AsyncSession):
        self.db = db
        # Use a chave do Groq que já validamos como funcional
        self.client = AsyncGroq(api_key=settings.groq_api_key)
        self.model_name = "llama-3.3-70b-versatile"

    async def chat(self, message: str, department_id: Any | None = None) -> Dict[str, Any]:
        """Processes a natural language message and returns an AI-powered read-only answer."""
        logger.info(f"Chat request via Groq: '{message}' (Dept: {department_id})")

        # 1. Identificar intenção. O chat é deliberadamente read-only.
        intent = await self._identify_intent(message)
        
        if intent.get("action") == "UPDATE_CATEGORY":
            return {
                "answer": (
                    "Por segurança, o chat de auditoria não altera o catálogo. "
                    "Faça correções de categoria pelo Catálogo, onde a ação passa por validação, "
                    "escopo do departamento e registro de auditoria."
                ),
                "intent_detected": intent,
                "action_performed": None,
                "blocked_reason": "audit_chat_is_read_only",
            }

        # 2. Se for uma pergunta, segue o fluxo normal de SQL
        sql_query = await self._generate_sql(message, department_id)
        logger.debug(f"Generated SQL: {sql_query}")

        if not self._is_read_only_sql(sql_query):
            logger.warning("Blocked unsafe SQL generated by audit chat.")
            return {
                "answer": (
                    "Não executei a consulta gerada porque ela não parece ser uma consulta "
                    "somente leitura. Reformule a pergunta para uma análise ou listagem."
                ),
                "error": "unsafe_sql_blocked",
            }

        safety_error = self._get_sql_safety_error(sql_query, department_id)
        if safety_error:
            logger.warning("Blocked audit chat SQL due to safety guard: %s", safety_error)
            return {
                "answer": (
                    "Não executei a consulta gerada porque ela não passou nas regras de "
                    "segurança e isolamento do chat de auditoria."
                ),
                "error": safety_error,
            }

        # 2. Execute SQL (ReadOnly)
        try:
            result = await self.db.execute(text(sql_query))
            # Converte Decimal para float para serialização JSON
            data = []
            for row in result.fetchall():
                row_dict = dict(row._mapping)
                for k, v in row_dict.items():
                    if isinstance(v, Decimal):
                        row_dict[k] = float(v)
                data.append(row_dict)
        except Exception as e:
            logger.error(f"SQL Execution failed: {e}")
            return {
                "answer": "Desculpe, tive um problema técnico ao consultar os dados. Pode tentar reformular a pergunta?",
                "error": str(e),
                "query_used": sql_query
            }

        # 3. Explain result
        answer = await self._explain_data(message, data)
        
        return {
            "answer": answer,
            "query_used": sql_query,
            "data_summary": data[:5]
        }

    @staticmethod
    def _is_read_only_sql(sql: str | None) -> bool:
        """Return True only for a single SELECT/WITH statement without write keywords."""

        if not sql:
            return False

        statement = sql.strip()
        if not statement:
            return False

        if ";" in statement.rstrip(";"):
            return False

        normalized = statement.rstrip(";").lstrip()
        if not re.match(r"^(select|with)\b", normalized, flags=re.IGNORECASE):
            return False

        forbidden = re.compile(
            r"\b("
            r"alter|analyze|call|copy|create|delete|do|drop|execute|grant|insert|"
            r"lock|merge|refresh|reset|revoke|set|truncate|update|vacuum"
            r")\b",
            flags=re.IGNORECASE,
        )
        return forbidden.search(normalized) is None

    @classmethod
    def _get_sql_safety_error(cls, sql: str, department_id: Any | None) -> str | None:
        """Return a stable error code when generated SQL violates chat safety rules."""

        if cls._contains_sensitive_sql(sql):
            return "sensitive_sql_blocked"

        scope_error = cls._get_allowlist_error(sql)
        if scope_error:
            return scope_error

        if department_id is not None and not cls._is_tenant_scoped_sql(sql, department_id):
            return "tenant_scope_missing"

        return None

    @staticmethod
    def _contains_sensitive_sql(sql: str) -> bool:
        sensitive_identifiers = re.compile(
            r"(?<![\w])("
            r"users|cpf|cnpj|chave_acesso|qr_code|url_sefaz|xml|json_bruto|"
            r"payload_bruto|payload_fiscal|raw_payload|hashed_password|email|"
            r"access_token|refresh_token"
            r")(?![\w])",
            flags=re.IGNORECASE,
        )
        return sensitive_identifiers.search(sql) is not None

    @classmethod
    def _get_allowlist_error(cls, sql: str) -> str | None:
        wildcard_pattern = r"\bselect\s+\*|\bselect\b[\s\S]*\b\w+\.\*"
        if re.search(wildcard_pattern, sql, flags=re.IGNORECASE):
            return "wildcard_sql_blocked"

        aliases = cls._extract_table_aliases(sql)
        if not aliases:
            return "table_not_allowed"

        for table_name in set(aliases.values()):
            if table_name == "__cte__":
                continue
            if table_name not in cls.ALLOWED_SQL_COLUMNS:
                return "table_not_allowed"

        for qualifier, column in re.findall(r"\b([A-Za-z_]\w*)\.([A-Za-z_]\w*)\b", sql):
            table_name = aliases.get(qualifier.lower())
            if table_name is None:
                return "table_not_allowed"
            if table_name == "__cte__":
                continue
            if column.lower() not in cls.ALLOWED_SQL_COLUMNS[table_name]:
                return "column_not_allowed"

        return None

    @classmethod
    def _extract_table_aliases(cls, sql: str) -> dict[str, str]:
        aliases: dict[str, str] = {}
        cte_names = cls._extract_cte_names(sql)
        reserved = {
            "where",
            "join",
            "left",
            "right",
            "inner",
            "outer",
            "full",
            "cross",
            "on",
            "group",
            "order",
            "limit",
            "offset",
            "having",
            "union",
        }
        table_pattern = re.compile(
            r"\b(?:from|join)\s+([A-Za-z_][\w.]*)"
            r"(?:\s+(?:as\s+)?([A-Za-z_]\w*))?",
            flags=re.IGNORECASE,
        )

        for raw_table, raw_alias in table_pattern.findall(sql):
            table_name = raw_table.split(".")[-1].lower()
            aliases[table_name] = "__cte__" if table_name in cte_names else table_name
            alias = raw_alias.lower() if raw_alias else ""
            if alias and alias not in reserved:
                aliases[alias] = "__cte__" if table_name in cte_names else table_name

        return aliases

    @staticmethod
    def _extract_cte_names(sql: str) -> set[str]:
        if not re.match(r"^\s*with\b", sql, flags=re.IGNORECASE):
            return set()

        return {
            match.group(1).lower()
            for match in re.finditer(
                r"(?:\bwith|,)\s+([A-Za-z_]\w*)\s+as\s*\(",
                sql,
                flags=re.IGNORECASE,
            )
        }

    @staticmethod
    def _is_tenant_scoped_sql(sql: str, department_id: Any) -> bool:
        department = re.escape(str(department_id))
        tenant_filter = re.compile(
            rf"(?<![\w])(?:\w+\.)?department_id\s*=\s*['\"]?{department}['\"]?",
            flags=re.IGNORECASE,
        )
        return tenant_filter.search(sql) is not None

    async def _generate_sql(self, prompt: str, department_id: Any | None) -> str:
        tenant_constraint = (
            f"Filtre os dados SEMPRE com department_id = '{department_id}' em consultas de usuários não-admin."
            if department_id
            else "Usuário admin: não aplique filtro de department_id automaticamente."
        )
        
        system_prompt = f"""
        Você é um Especialista em Banco de Dados PostgreSQL da Auditoria Governamental.
        Seu objetivo é traduzir a pergunta do usuário para uma ÚNICA query SQL SELECT válida.

        {self.SCHEMA_CONTEXT}

        REGRAS CRÍTICAS:
        1. Use APENAS SELECT. Nunca use comandos de modificação.
        2. {tenant_constraint}
        3. Use somente as tabelas e colunas listadas acima.
        4. Nunca use SELECT *.
        5. Nunca selecione CPF, CNPJ, chave fiscal, QR Code, URL SEFAZ, XML, JSON bruto, payload fiscal ou dados de usuários.
        6. Retorne EXCLUSIVAMENTE o código SQL, sem markdown, sem explicações.
        7. Sempre limite a 50 resultados para performance.
        """
        
        chat_completion = await self.client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": prompt},
            ],
            model=self.model_name,
            temperature=0.1,
        )
        
        sql = chat_completion.choices[0].message.content.replace("```sql", "").replace("```", "").strip()
        return sql

    async def _explain_data(self, question: str, data: List[Dict]) -> str:
        if not data:
            return "Não encontrei nenhum registro que corresponda à sua pergunta no banco de dados."

        system_prompt = """
        Você é um Auditor Sênior amigável e especialista em análise de compras governamentais.
        Sua tarefa é explicar os resultados de uma consulta ao banco de dados de forma clara e profissional.
        Seja conciso e use português do Brasil.
        """
        
        user_prompt = f"""
        A pergunta feita foi: "{question}"
        
        Os dados encontrados no banco foram:
        {json.dumps(data[:20], ensure_ascii=False, indent=2)}

        Explique o que esses dados significam em relação à pergunta.
        """
        
        chat_completion = await self.client.chat.completions.create(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            model=self.model_name,
            temperature=0.5,
        )
        return chat_completion.choices[0].message.content.strip()

    async def _identify_intent(self, message: str) -> Dict[str, Any]:
        """Identifica se o usuário quer apenas perguntar (SELECT) ou corrigir algo (UPDATE)."""
        prompt = f"""
        Analise a mensagem do usuário e identifique a intenção.
        MENSAGEM: "{message}"

        OPÇÕES DE INTENÇÃO:
        1. QUERY: Pergunta geral sobre dados.
        2. UPDATE_CATEGORY: O usuário quer mudar a categoria de um produto.
           Campos extraídos: {{"ean": "...", "nova_categoria": "..."}}

        Retorne APENAS um JSON no formato: {{"action": "QUERY" | "UPDATE_CATEGORY", "ean": "...", "nova_categoria": "..."}}
        """
        
        chat_completion = await self.client.chat.completions.create(
            messages=[
                {"role": "system", "content": "Responda apenas JSON válido."},
                {"role": "user", "content": prompt},
            ],
            model=self.model_name,
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        return json.loads(chat_completion.choices[0].message.content)
