"""fase_1h_1_multi_tenant_hardening

Revision ID: 8bb1952a2e94
Revises: a1b2c3d4e5f6
Create Date: 2026-05-31 17:58:10.358485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb1952a2e94'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classificacao_cache', 'verificado_usuario',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('fornecedores', sa.Column('department_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=False)
    op.create_index(op.f('ix_fornecedores_department_id'), 'fornecedores', ['department_id'], unique=False)
    op.create_unique_constraint('uq_fornecedores_cnpj_dept', 'fornecedores', ['cnpj', 'department_id'])
    op.create_foreign_key(None, 'fornecedores', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('uq_notas_fiscais_chave_acesso'), 'notas_fiscais', type_='unique')
    op.drop_index(op.f('ix_notas_fiscais_chave_acesso'), table_name='notas_fiscais')
    op.create_index(op.f('ix_notas_fiscais_chave_acesso'), 'notas_fiscais', ['chave_acesso'], unique=False)
    op.create_unique_constraint('uq_notas_fiscais_chave_acesso_dept', 'notas_fiscais', ['chave_acesso', 'department_id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint('uq_users_email_dept', 'users', ['email', 'department_id'])
    op.create_unique_constraint('uq_users_username_dept', 'users', ['username', 'department_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_username_dept', 'users', type_='unique')
    op.drop_constraint('uq_users_email_dept', 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('uq_notas_fiscais_chave_acesso_dept', 'notas_fiscais', type_='unique')
    op.drop_index(op.f('ix_notas_fiscais_chave_acesso'), table_name='notas_fiscais')
    op.create_index(op.f('ix_notas_fiscais_chave_acesso'), 'notas_fiscais', ['chave_acesso'], unique=True)
    op.create_unique_constraint(op.f('uq_notas_fiscais_chave_acesso'), 'notas_fiscais', ['chave_acesso'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'fornecedores', type_='foreignkey')
    op.drop_constraint('uq_fornecedores_cnpj_dept', 'fornecedores', type_='unique')
    op.drop_index(op.f('ix_fornecedores_department_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.drop_column('fornecedores', 'department_id')
    op.alter_column('classificacao_cache', 'verificado_usuario',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
