"""Add department_id to AuditLog

Revision ID: c3badba95526
Revises: c116a0fe06f6
Create Date: 2026-05-25 15:43:14.482103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3badba95526'
down_revision: Union[str, Sequence[str], None] = 'c116a0fe06f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_department_id'), 'audit_logs', ['department_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_department_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'department_id')
    # ### end Alembic commands ###
