"""Add Department model and Multi-tenancy support

Revision ID: f8ae376b9336
Revises: bb2cbc82fb14
Create Date: 2026-05-25 14:50:08.711805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ae376b9336'
down_revision: Union[str, Sequence[str], None] = 'bb2cbc82fb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.add_column('notas_fiscais', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notas_fiscais_department_id'), 'notas_fiscais', ['department_id'], unique=False)
    op.create_foreign_key(None, 'notas_fiscais', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_column('users', 'department_id')
    op.drop_constraint(None, 'notas_fiscais', type_='foreignkey')
    op.drop_index(op.f('ix_notas_fiscais_department_id'), table_name='notas_fiscais')
    op.drop_column('notas_fiscais', 'department_id')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
