# -*- coding: utf-8 -*-
"""
Script para popular o banco de dados com 500 produtos de treinamento.

- Cria/garante as tabelas: produtos, historico_precos
- Limpa as tabelas antes de inserir
- Insere os 500 produtos com:
    - ean (id gerado por hash)
    - nome_original
    - nome_limpo (versão simplificada)
    - marca (se reconhecer)
    - categoria (ALIMENTOS BÁSICOS, HORTIFRUTI, etc.)
    - unidade (kg, g, l, ml, un, etc.)
- Gera registros fictícios de compras em historico_precos
"""

import os
import sys
import re
import random
import hashlib
from datetime import datetime, timedelta

import psycopg2
from psycopg2 import Error
from dotenv import load_dotenv

# Permite imports relativos se precisar no futuro
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

load_dotenv()

# Configuração do Banco de Dados
LINK_BANCO = os.getenv("DATABASE_URL")

if not LINK_BANCO:
    print("❌ ERRO: URL do banco de dados não encontrada no arquivo .env (DATABASE_URL).")
    raise SystemExit(1)


# -----------------------------------------------------------------------------
# Conexão e criação de tabelas
# -----------------------------------------------------------------------------
def conectar():
    """Estabelece conexão com o banco de dados PostgreSQL."""
    try:
        conn = psycopg2.connect(LINK_BANCO)
        return conn
    except Error as e:
        print(f"❌ ERRO ao conectar ao banco de dados: {e}")
        raise


def criar_tabelas_se_nao_existirem():
    """Cria as tabelas necessárias (produtos, historico_precos) se não existirem."""
    conn = conectar()
    cursor = conn.cursor()

    try:
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS produtos (
                ean           VARCHAR(50) PRIMARY KEY,
                nome_original TEXT NOT NULL,
                nome_limpo    VARCHAR(255) NOT NULL,
                marca         VARCHAR(100),
                categoria     VARCHAR(100) NOT NULL,
                unidade       VARCHAR(20) NOT NULL
            );
        """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS historico_precos (
                id           SERIAL PRIMARY KEY,
                ean          VARCHAR(50) REFERENCES produtos(ean),
                data_compra  DATE NOT NULL,
                mercado      VARCHAR(255) NOT NULL,
                preco_pago   NUMERIC(10,2) NOT NULL,
                quantidade   NUMERIC(10,3) NOT NULL
            );
        """
        )

        conn.commit()
        print("✅ Tabelas verificadas/criadas com sucesso")
    except Exception as e:
        print(f"❌ ERRO ao criar tabelas: {e}")
        conn.rollback()
    finally:
        cursor.close()
        conn.close()


# -----------------------------------------------------------------------------
# Funções auxiliares: marca, unidade, nome_limpo
# -----------------------------------------------------------------------------
def extrair_marca(nome: str) -> str:
    """Extrai uma marca conhecida a partir do nome do produto (se houver)."""
    marcas_conhecidas = [
        "NINHO",
        "TIROLEZ",
        "ITAMBÉ",
        "VIGOR",
        "PILÃO",
        "UNIÃO",
        "CISNE",
        "LIZA",
        "DONA BENTA",
        "YOKI",
        "PIMEL",
        "NESTLÉ",
        "MELITTA",
        "NESCAFÉ",
        "HERCIL",
        "VILA VELHA",
        "ROYAL",
        "QUAKER",
        "FRESCLAT",
        "SAZON",
        "GALLO",
        "NISSIN",
        "NESCAU",
        "KNORR",
        "TANG",
        "DOVE",
        "CLEAR",
        "COLGATE",
        "REXONA",
        "LISTERINE",
        "NIVEA",
        "ORAL-B",
        "SENSODYNE",
        "VENZON",
        "OMO",
        "YPÊ",
        "LIMPOL",
        "PINHO SOL",
        "AJAX",
        "QBOA",
        "ACE",
        "DOWNY",
        "CIF",
        "ELMA CHIPS",
        "GAROTO",
        "PIRACANJUBA",
        "DEL VALE",
        "CRYSTAL",
        "SKOL",
        "RED BULL",
        "LEÃO",
        "ANTARCTICA",
        "ITAIPAVA",
        "MONSTER",
        "GATORADE",
        "HEINEKEN",
        "PEPSI",
        "CORONA",
        "BUDWEISER",
        "TRAMONTINA",
        "HAVAIANAS",
    ]

    nome_upper = nome.upper()
    for marca in marcas_conhecidas:
        if marca in nome_upper:
            return marca
    return ""


def determinar_unidade(nome: str) -> str:
    """Determina a unidade de medida baseada no nome do produto."""
    nome_lower = nome.lower()

    padroes = [
        (r"(\d+\.?\d*)\s*kg\b", "kg"),
        (r"(\d+\.?\d*)\s*g\b", "g"),
        (r"(\d+\.?\d*)\s*l\b", "l"),
        (r"(\d+\.?\d*)\s*ml\b", "ml"),
        (r"\bkg\b", "kg"),
        (r"\bg\b", "g"),
        (r"\bl\b", "l"),
        (r"\bml\b", "ml"),
        (r"\bun\b", "un"),
        (r"\bpct\b", "pct"),
        (r"\bcx\b", "cx"),
        (r"\bcaixa\b", "cx"),
        (r"\bcento\b", "un"),
        (r"(\d+)\s*unidades?\b", "un"),
    ]

    for padrao, unidade in padroes:
        if re.search(padrao, nome_lower):
            return unidade

    # Fallback por tipo
    if any(p in nome_lower for p in ["leite", "refri", "suco", "água", "cerveja", "vinho"]):
        return "l"
    if any(p in nome_lower for p in ["biscoito", "salgadinho", "chocolate", "bombom", "bala"]):
        return "g" if "g" in nome_lower else "un"
    if any(p in nome_lower for p in ["arroz", "feijão", "açúcar", "farinha", "macarrão"]):
        return "kg" if "kg" in nome_lower else "g"

    return "un"


def gerar_nome_limpo(nome_original: str, marca: str | None = None) -> str:
    """
    Gera um nome_limpo simplificado para o produto,
    removendo marca, quantidade e unidades óbvias.
    """
    tokens = nome_original.strip().split()
    resultado = []
    marca_upper = (marca or "").upper()

    for t in tokens:
        t_limpo = t.strip(",").upper()

        # Remove marca
        if marca_upper and marca_upper in t_limpo:
            continue

        # Remove tokens de unidade / quantidade
        if t_limpo in {"KG", "G", "ML", "L", "UN", "PCT", "CX"}:
            continue
        if t_limpo.replace(",", "").replace(".", "").isdigit():
            continue

        resultado.append(t_limpo)

    if not resultado:
        return nome_original.upper()

    # Pega até 3 palavras principais
    return " ".join(resultado[:3])


# -----------------------------------------------------------------------------
# Lista dos 500 produtos (exatamente como você mandou)
# -----------------------------------------------------------------------------
def processar_lista_produtos():
    """Processa a lista de 500 produtos e devolve uma lista [(nome, categoria), ...]."""

    produtos_texto = """
1. ARROZ AGULHA 5KG, ALIMENTOS BÁSICOS
2. FEIJÃO CARIOCA 1KG, ALIMENTOS BÁSICOS
3. AÇÚCAR REFINADO UNIÃO 1KG, ALIMENTOS BÁSICOS
4. CAFÉ PILÃO 500G, ALIMENTOS BÁSICOS
5. SAL REFINADO CISNE 1KG, ALIMENTOS BÁSICOS
6. ÓLEO DE SOJA LIZA 900ML, ALIMENTOS BÁSICOS
7. ARROZ PARBOILIZADO TIO JOÃO 5KG, ALIMENTOS BÁSICOS
8. FEIJÃO PRETO 1KG, ALIMENTOS BÁSICOS
9. AÇÚCAR CRISTAL DOÇULA 1KG, ALIMENTOS BÁSICOS
10. CAFÉ EXTRA FORTE MELITTA 500G, ALIMENTOS BÁSICOS
11. SAL GROSSO CISNE 1KG, ALIMENTOS BÁSICOS
12. ÓLEO DE GIRASSOL LIZA 900ML, ALIMENTOS BÁSICOS
13. FARINHA DE TRIGO DONA BENTA 1KG, ALIMENTOS BÁSICOS
14. MACARRÃO SEM OVOS YOKI 500G, ALIMENTOS BÁSICOS
15. MEL DE ABELHA PIMEL 500G, ALIMENTOS BÁSICOS
16. ARROZ 7 GRÃOS 1KG, ALIMENTOS BÁSICOS
17. FEIJÃO FRADINHO 1KG, ALIMENTOS BÁSICOS
18. AÇÚCAR LIGHT 1KG, ALIMENTOS BÁSICOS
19. CAFÉ SOLÚVEL NESCAFÉ 100G, ALIMENTOS BÁSICOS
20. SAL LIGHT HERCIL 1KG, ALIMENTOS BÁSICOS
21. ÓLEO DE CANOLA VILA VELHA 900ML, ALIMENTOS BÁSICOS
22. FARINHA DE MANDIOCA YOKI 500G, ALIMENTOS BÁSICOS
23. MACARRÃO INTEGRAL 500G, ALIMENTOS BÁSICOS
24. GRANOLA NATUREZA 500G, ALIMENTOS BÁSICOS
25. ARROZ JASMIM 1KG, ALIMENTOS BÁSICOS
26. FEIJÃO VERDE 1KG, ALIMENTOS BÁSICOS
27. AÇÚCAR DE CONFEITEIRO 500G, ALIMENTOS BÁSICOS
28. CAFÉ EM CÁPSULAS NESPRESSO 10UN, ALIMENTOS BÁSICOS
29. SAL COM ALHO 1KG, ALIMENTOS BÁSICOS
30. ÓLEO / AZEITE PORTUGUÊS 250ML, ALIMENTOS BÁSICOS
31. FERMENTO EM PÓ ROYAL 100G, ALIMENTOS BÁSICOS
32. MACARRÃO PARA SOPA 500G, ALIMENTOS BÁSICOS
33. AVEIA EM FLOCOS QUAKER 500G, ALIMENTOS BÁSICOS
34. ARROZ ARBORIO 1KG, ALIMENTOS BÁSICOS
35. FEIJÃO DE CORDA 1KG, ALIMENTOS BÁSICOS
36. ADOÇANTE LIQUIDO FRESCLAT 200ML, ALIMENTOS BÁSICOS
37. CAFÉ DESCAFINADO 500G, ALIMENTOS BÁSICOS
38. SAL MARINHO MOÍDO 500G, ALIMENTOS BÁSICOS
39. ÓLEO DE MILHO 900ML, ALIMENTOS BÁSICOS
40. FARINHA DE ROSCA 500G, ALIMENTOS BÁSICOS
41. MACARRÃO COM OVOS 500G, ALIMENTOS BÁSICOS
42. LINHAÇA DOURADA 200G, ALIMENTOS BÁSICOS
43. ARROZ SÉTIMO CÉU 5KG, ALIMENTOS BÁSICOS
44. FEIJÃO BOLINHA 1KG, ALIMENTOS BÁSICOS
45. GLÚTEN EM PÓ 500G, ALIMENTOS BÁSICOS
46. CAFÉ GOURMET EM GRÃOS 500G, ALIMENTOS BÁSICOS
47. TEMPERO SAZON 60G, ALIMENTOS BÁSICOS
48. AZEITE EXTRA VIRGEM GALLO 500ML, ALIMENTOS BÁSICOS
49. POLVILHO DOCE YOKI 500G, ALIMENTOS BÁSICOS
50. MACARRÃO INSTANTÂNEO NISSIN 85G, ALIMENTOS BÁSICOS
51. CHOCOLATE EM PÓ NESCAU 400G, ALIMENTOS BÁSICOS
52. ARROZ CATETO 1KG, ALIMENTOS BÁSICOS
53. FEIJÃO JALO 1KG, ALIMENTOS BÁSICOS
54. AÇÚCAR MASCAVO 1KG, ALIMENTOS BÁSICOS
55. CAFÉ EM PÓ FORTE 1KG, ALIMENTOS BÁSICOS
56. SAL DEFUMADO 200G, ALIMENTOS BÁSICOS
57. ÓLEO DE COCONHA 200ML, ALIMENTOS BÁSICOS
58. FUBÁ YOKI 500G, ALIMENTOS BÁSICOS
59. MACARRÃO LASANHA 500G, ALIMENTOS BÁSICOS
60. GERME DE TRIGO 200G, ALIMENTOS BÁSICOS
61. ARROZ NEGRO 500G, ALIMENTOS BÁSICOS
62. FEIJÃO AZEITE 1KG, ALIMENTOS BÁSICOS
63. LEITE DE COCO 200ML, ALIMENTOS BÁSICOS
64. CAFÉ COM LEITE EM PÓ 200G, ALIMENTOS BÁSICOS
65. SAL FLOR DE SAL 200G, ALIMENTOS BÁSICOS
66. AZEITE TRUFADO 100ML, ALIMENTOS BÁSICOS
67. FARINHA DE AMÊNDOA 200G, ALIMENTOS BÁSICOS
68. MACARRÃO PENE 500G, ALIMENTOS BÁSICOS
69. PÃO DE FORMA SEM CASCA 500G, ALIMENTOS BÁSICOS
70. ARROZ VERMELHO 500G, ALIMENTOS BÁSICOS
71. FEIJÃO ROXINHO 1KG, ALIMENTOS BÁSICOS
72. CALDO DE GALINHA KNORR 1KG, ALIMENTOS BÁSICOS
73. CAFÉ CAPPUCCINO EM PÓ 200G, ALIMENTOS BÁSICOS
74. ÓLEO DE LINHAÇA 200ML, ALIMENTOS BÁSICOS
75. MISTURA PARA BOLO YOKI 500G, ALIMENTOS BÁSICOS
76. MACARRÃO CONCHINHA 500G, ALIMENTOS BÁSICOS
77. SUCO EM PÓ TANG 45G, ALIMENTOS BÁSICOS
78. ARROZ DOCE 500G, ALIMENTOS BÁSICOS
79. FEIJÃO MULATINHO 1KG, ALIMENTOS BÁSICOS
80. VINAGRE DE MAÇÃ 300ML, ALIMENTOS BÁSICOS
81. BANANA PRATA KG, HORTIFRUTI
82. BATATA ASTERIX KG, HORTIFRUTI
83. TOMATE CEREJA KG, HORTIFRUTI
84. CEBOLA KG, HORTIFRUTI
85. ALHO KG, HORTIFRUTI
86. LARANJA PERA KG, HORTIFRUTI
87. LIMÃO TAITI KG, HORTIFRUTI
88. MAÇÃ FUJI KG, HORTIFRUTI
89. CENOURA KG, HORTIFRUTI
90. PIMENTÃO VERMELHO KG, HORTIFRUTI
91. ABACAXI KG, HORTIFRUTI
92. MAMÃO PAPAIA KG, HORTIFRUTI
93. MANGA TOMMY KG, HORTIFRUTI
94. UVA ITÁLIA KG, HORTIFRUTI
95. GOIABA KG, HORTIFRUTI
96. MORANGO KG, HORTIFRUTI
97. BETERRABA KG, HORTIFRUTI
98. ABOBRINHA KG, HORTIFRUTI
99. CHUCHU KG, HORTIFRUTI
100. REPOLHO ROXO KG, HORTIFRUTI
101. BANANA NANICA KG, HORTIFRUTI
102. BATATA DOCE KG, HORTIFRUTI
103. TOMATE ITALIANO KG, HORTIFRUTI
104. CEBOLA ROXA KG, HORTIFRUTI
105. ALHO PORÓ KG, HORTIFRUTI
106. LARANJA BAHIA KG, HORTIFRUTI
107. LIMÃO SICILIANO KG, HORTIFRUTI
108. MAÇÃ GALA KG, HORTIFRUTI
109. CENOURA BABY 200G, HORTIFRUTI
110. PIMENTÃO AMARELO KG, HORTIFRUTI
111. ABACATE KG, HORTIFRUTI
112. MAMÃO FORMOSA KG, HORTIFRUTI
113. MANGA ESPADA KG, HORTIFRUTI
114. UVA RUBI KG, HORTIFRUTI
115. PERA KG, HORTIFRUTI
116. KIWI KG, HORTIFRUTI
117. BERINJELA KG, HORTIFRUTI
118. MAXIXE KG, HORTIFRUTI
119. COUVE FLOR KG, HORTIFRUTI
120. RÚCULA KG, HORTIFRUTI
121. BANANA MAÇÃ KG, HORTIFRUTI
122. BATATA BAROA KG, HORTIFRUTI
123. TOMATE KG, HORTIFRUTI
124. CEBOLA CAIPIRA KG, HORTIFRUTI
125. ALHO PÉROLA KG, HORTIFRUTI
126. LARANJA LIMA KG, HORTIFRUTI
127. MAÇÃ VERDE KG, HORTIFRUTI
128. PIMENTÃO VERDE KG, HORTIFRUTI
129. MELANCIA KG, HORTIFRUTI
130. MELÃO KG, HORTIFRUTI
131. PÊSSEGO KG, HORTIFRUTI
132. NECTARINA KG, HORTIFRUTI
133. AMEIXA KG, HORTIFRUTI
134. FIGO KG, HORTIFRUTI
135. JILÓ KG, HORTIFRUTI
136. PEPINO KG, HORTIFRUTI
137. QUIABO KG, HORTIFRUTI
138. ALFACE CRESPA KG, HORTIFRUTI
139. ALFACE AMERICANA KG, HORTIFRUTI
140. ESPINAFRE KG, HORTIFRUTI
141. LEITE INTEGRAL NINHO 1L, LATICÍNIOS
142. QUEIJO MUSSARELA TIROLEZ 200G, LATICÍNIOS
143. IOGURTE NATURAL ITAMBÉ 170G, LATICÍNIOS
144. REQUEIJÃO CREMOSO VIGOR 200G, LATICÍNIOS
145. MANTEIGA COM SAL AVIAMENTO 500G, LATICÍNIOS
146. LEITE SEMIDESNATADO ITAMBÉ 1L, LATICÍNIOS
147. QUEIJO PRATO FATIADO 150G, LATICÍNIOS
148. IOGURTE DE FRUTAS YOGURTE 170G, LATICÍNIOS
149. PETIT SUISSE DANONE 60G, LATICÍNIOS
150. CREME DE LEITE NESTLÉ 200G, LATICÍNIOS
151. LEITE DESNATADO ITAMBÉ 1L, LATICÍNIOS
152. QUEIJO MINAS FRESCAL 500G, LATICÍNIOS
153. IOGURTE BEBÍVEL BATAVO 1L, LATICÍNIOS
154. RICOTA TIROLEZ 200G, LATICÍNIOS
155. MARGARINA DELICATA 500G, LATICÍNIOS
156. LEITE CONDENSADO MOÇA 395G, LATICÍNIOS
157. QUEIJO COALHO 200G, LATICÍNIOS
158. IOGURTE GREGO NATURAL 170G, LATICÍNIOS
159. MUSSARELA DE BÚFALA 150G, LATICÍNIOS
160. CHANTILLY EM PÓ 100G, LATICÍNIOS
161. LEITE FERMENTADO YAKULT 100ML, LATICÍNIOS
162. QUEIJO PARMESÃO RALADO 100G, LATICÍNIOS
163. IOGURTE LIGHT 170G, LATICÍNIOS
164. QUEIJO CHEDDAR 150G, LATICÍNIOS
165. DOCE DE LEITE PASTOSO 500G, LATICÍNIOS
166. LEITE EM PÓ INTEGRAL 400G, LATICÍNIOS
167. QUEIJO GOUDA 150G, LATICÍNIOS
168. IOGURTE SABOR MORANGO 170G, LATICÍNIOS
169. QUEIJO PROVOLONE 200G, LATICÍNIOS
170. BECHAMEL PRONTO 200G, LATICÍNIOS
171. LEITE DE CABRA 1L, LATICÍNIOS
172. QUEIJO EMENTAL 150G, LATICÍNIOS
173. IOGURTE SABOR LIMÃO 170G, LATICÍNIOS
174. QUEIJO GORGONZOLA 150G, LATICÍNIOS
175. PO DE QUEIJO 100G, LATICÍNIOS
176. LEITE FORTIFICADO ADULTO 1L, LATICÍNIOS
177. QUEIJO MINAS PADRÃO 500G, LATICÍNIOS
178. IOGURTE ZERO LACTOSE 170G, LATICÍNIOS
179. QUEIJO SUIÇO 150G, LATICÍNIOS
180. FLAN DE BAUNILHA 100G, LATICÍNIOS
181. LEITE DE SOJA ORIGINAL 1L, LATICÍNIOS
182. QUEIJO COTTAGE 150G, LATICÍNIOS
183. IOGURTE COM GRANOLA 170G, LATICÍNIOS
184. QUEIJO ESTEPE 150G, LATICÍNIOS
185. MANTEIGA GOURMET SEM SAL 200G, LATICÍNIOS
186. LEITE EVAPORADO 1L, LATICÍNIOS
187. QUEIJO TIROLEZ FATIADO 150G, LATICÍNIOS
188. IOGURTE PROBIÓTICO 170G, LATICÍNIOS
189. QUEIJO RICOTA LIGHT 200G, LATICÍNIOS
190. CREPE DE QUEIJO 200G, LATICÍNIOS
191. LEITE AROMATIZADO MORANGO 1L, LATICÍNIOS
192. QUEIJO MINAS LARGATO 500G, LATICÍNIOS
193. IOGURTE DE POTE 1KG, LATICÍNIOS
194. QUEIJO MAASDAM 150G, LATICÍNIOS
195. MANTEIGA DE GARRAFA 500G, LATICÍNIOS
196. LEITE EM PÓ DESNATADO 400G, LATICÍNIOS
197. QUEIJO FRESCAL LIGHT 500G, LATICÍNIOS
198. IOGURTE SABOR UVA 170G, LATICÍNIOS
199. QUEIJO TILSIT 150G, LATICÍNIOS
200. GELATINA DE LEITE 100G, LATICÍNIOS
201. LEITE DE AVEIA 1L, LATICÍNIOS
202. QUEIJO QUARK 200G, LATICÍNIOS
203. IOGURTE SABOR PÊSSEGO 170G, LATICÍNIOS
204. QUEIJO LANCHE 200G, LATICÍNIOS
205. PUDIM DE LEITE 100G, LATICÍNIOS
206. LEITE DE AMÊNDOA 1L, LATICÍNIOS
207. QUEIJO FRESCAL 500G, LATICÍNIOS
208. IOGURTE SABOR COCO 170G, LATICÍNIOS
209. QUEIJO GRUYÈRE 150G, LATICÍNIOS
210. SOBREMESA DE SAGU 100G, LATICÍNIOS
211. LAVA ROUPAS LIQ OMO 3L, LIMPEZA
212. AMACIANTE YPÊ 2L, LIMPEZA
213. DETERGENTE LIMPOL 500ML, LIMPEZA
214. DESINFETANTE PINHO SOL 2L, LIMPEZA
215. LIMPADOR MULTIUSO AJAX 1L, LIMPEZA
216. ÁGUA SANITÁRIA QBOA 2L, LIMPEZA
217. LAVA ROUPAS EM PÓ OMO 2KG, LIMPEZA
218. AMACIANTE FLOR 2L, LIMPEZA
219. DETERGENTE LÍQUIDO YPÊ 500ML, LIMPEZA
220. DESINFETANTE LAVANDA 2L, LIMPEZA
221. LIMPADOR DE VIDROS VEJA 500ML, LIMPEZA
222. ALVEJANTE EM PÓ 1KG, LIMPEZA
223. LAVA ROUPAS LIQ BRILHANTE 3L, LIMPEZA
224. AMACIANTE MONBIJU 2L, LIMPEZA
225. DETERGENTE EM PÓ 1KG, LIMPEZA
226. DESINFETANTE CÍTRICOS 2L, LIMPEZA
227. LIMPADOR DE PISOS CIF 1L, LIMPEZA
228. SABÃO EM PÓ 1KG, LIMPEZA
229. LAVA ROUPAS LIQ MINUANO 3L, LIMPEZA
230. AMACIANTE COM SOFT 2L, LIMPEZA
231. DETERGENTE NEUTRO 500ML, LIMPEZA
232. DESINFETANTE EUCALIPTO 2L, LIMPEZA
233. LIMPADOR DE MÓVEIS 500ML, LIMPEZA
234. SABÃO EM BARRA COZINHA 5UN, LIMPEZA
235. LAVA ROUPAS EM PÓ ACE 1KG, LIMPEZA
236. AMACIANTE CHEIRO DE VERÃO 2L, LIMPEZA
237. DETERGENTE DE LARANJA 500ML, LIMPEZA
238. DESINFETANTE GARDENIA 2L, LIMPEZA
239. LIMPADOR DE BANHEIRO 1L, LIMPEZA
240. LIMPADOR CREMOSO 500G, LIMPEZA
241. LAVA LOUÇA LIQ LIMPOL 500ML, LIMPEZA
242. AMACIANTE CONDOR 2L, LIMPEZA
243. DETERGENTE DE MAÇÃ VERDE 500ML, LIMPEZA
244. DESINFETANTE JASMIM 2L, LIMPEZA
245. LIMPADOR DE COZINHA 1L, LIMPEZA
246. SABÃO EM PÓ LÍQUIDO 3L, LIMPEZA
247. LAVA ROUPAS LIQ DOWNY 3L, LIMPEZA
248. AMACIANTE KAIENKO 2L, LIMPEZA
249. DETERGENTE DE COCO 500ML, LIMPEZA
250. DESINFETANTE MARROM 2L, LIMPEZA
251. LIMPADOR DE INOX 500ML, LIMPEZA
252. SABÃO EM BARRA 5UN, LIMPEZA
253. LAVA LOUÇA EM PÓ 500G, LIMPEZA
254. AMACIANTE LILAS 2L, LIMPEZA
255. DETERGENTE DE LIMÃO 500ML, LIMPEZA
256. DESINFETANTE ROSA 2L, LIMPEZA
257. LIMPADOR DE PRATA 200ML, LIMPEZA
258. SODA CÁUSTICA 1KG, LIMPEZA
259. LAVA ROUPAS LIQ ALA 3L, LIMPEZA
260. AMACIANTE CAMPO MINADO 2L, LIMPEZA
261. DETERGENTE DE PINHO 500ML, LIMPEZA
262. DESINFETANTE VERDE 2L, LIMPEZA
263. LIMPADOR DE COURO 500ML, LIMPEZA
264. SABÃO EM FLOCOS 500G, LIMPEZA
265. LAVA LOUÇA EM TABLETES 30UN, LIMPEZA
266. AMACIANTE CERISE 2L, LIMPEZA
267. DETERGENTE DE ERVAS 500ML, LIMPEZA
268. DESINFETANTE ALCACHOFRA 2L, LIMPEZA
269. LIMPADOR DE PAREDES 1L, LIMPEZA
270. DESENGORDURANTE DE COZINHA 1L, LIMPEZA
271. SABONETE EM BARRA DOVE 90G, HIGIENE PESSOAL
272. SHAMPOO CLEAR MEN 400ML, HIGIENE PESSOAL
273. CREME DENTAL COLGATE 90G, HIGIENE PESSOAL
274. DESODORANTE REXONA 90G, HIGIENE PESSOAL
275. ENXAGUANTE BUCAL LISTERINE 500ML, HIGIENE PESSOAL
276. SABONETE LÍQUIDO NIVEA 250ML, HIGIENE PESSOAL
277. CONDICIONADOR CLEAR MEN 400ML, HIGIENE PESSOAL
278. ESCOVA DE DENTE ORAL-B 1UN, HIGIENE PESSOAL
279. DESODORANTE AEROSSOL NIVEA 150ML, HIGIENE PESSOAL
280. PASTA DE DENTE SENSODYNE 90G, HIGIENE PESSOAL
281. SABONETE ÍNTIMO LUZ 250ML, HIGIENE PESSOAL
282. SHAMPOO SÉRUM SEDUÇÃO 400ML, HIGIENE PESSOAL
283. CONDICIONADOR SÉRUM SEDUÇÃO 400ML, HIGIENE PESSOAL
284. FIO DENTAL ORAL-B 50M, HIGIENE PESSOAL
285. DESODORANTE ROLL-ON DOVE 50G, HIGIENE PESSOAL
286. ANTITRANSPIRANTE VENZON 90G, HIGIENE PESSOAL
287. SABÃO EM PEDRA TIPO 1 5UN, HIGIENE PESSOAL
288. SHAMPOO ANTIQUEDA 400ML, HIGIENE PESSOAL
289. CONDICIONADOR ANTIQUEDA 400ML, HIGIENE PESSOAL
290. CREME PARA ASAS AXILAS 50G, HIGIENE PESSOAL
291. DESODORANTE EM CREME 50G, HIGIENE PESSOAL
292. SABONETE GLICERINA 3UN, HIGIENE PESSOAL
293. SHAMPOO INFANTIL 400ML, HIGIENE PESSOAL
294. CONDICIONADOR INFANTIL 400ML, HIGIENE PESSOAL
295. ÁGUA OXIGENADA 10VOL 100ML, HIGIENE PESSOAL
296. DESODORANTE FEMININO NIVEA 90G, HIGIENE PESSOAL
297. SABONETE ACNE 3UN, HIGIENE PESSOAL
298. SHAMPOO COLORAÇÃO 400ML, HIGIENE PESSOAL
299. CONDICIONADOR COLORAÇÃO 400ML, HIGIENE PESSOAL
300. PASTA DE DENTE BRANQUEADOR 90G, HIGIENE PESSOAL
301. DESODORANTE COM PROTEÇÃO SOLAR 90G, HIGIENE PESSOAL
302. SABONETE EXFOLIANTE 1UN, HIGIENE PESSOAL
303. SHAMPOO ÓLEO DE ARGAN 400ML, HIGIENE PESSOAL
304. CONDICIONADOR ÓLEO DE ARGAN 400ML, HIGIENE PESSOAL
305. ENXAGUANTE BUCAL SEM ÁLCOOL 500ML, HIGIENE PESSOAL
306. DESODORANTE CLÍNICO 90G, HIGIENE PESSOAL
307. SABONETE DE ERVAS 3UN, HIGIENE PESSOAL
308. SHAMPOO ANTICASPA 400ML, HIGIENE PESSOAL
309. CONDICIONADOR ANTICASPA 400ML, HIGIENE PESSOAL
310. ESCOVA DE DENTE ELÉTRICA 1UN, HIGIENE PESSOAL
311. DESODORANTE EM BARRA 90G, HIGIENE PESSOAL
312. SABONETE LÍQUIDO INFANTIL 250ML, HIGIENE PESSOAL
313. SHAMPOO POSTO SOLAR 400ML, HIGIENE PESSOAL
314. CONDICIONADOR POSTO SOLAR 400ML, HIGIENE PESSOAL
315. COTONETE 100UN, HIGIENE PESSOAL
316. DESODORANTE MINERAL 90G, HIGIENE PESSOAL
317. SABONETE DE ENXOFRE 3UN, HIGIENE PESSOAL
318. SHAMPOO VOLUME 400ML, HIGIENE PESSOAL
319. CONDICIONADOR VOLUME 400ML, HIGIENE PESSOAL
320. HIDRATANTE LABIAL 10G, HIGIENE PESSOAL
321. DESODORANTE SPORT 90G, HIGIENE PESSOAL
322. SABONETE ANTISÉPTICO 3UN, HIGIENE PESSOAL
323. SHAMPOO RECONSTRUÇÃO 400ML, HIGIENE PESSOAL
324. CONDICIONADOR RECONSTRUÇÃO 400ML, HIGIENE PESSOAL
325. PASTA DE DENTE INFANTIL 50G, HIGIENE PESSOAL
326. DESODORANTE PERFUMADO 90G, HIGIENE PESSOAL
327. SABONETE HIDRATANTE 3UN, HIGIENE PESSOAL
328. SHAMPOO MATIFICAÇÃO 400ML, HIGIENE PESSOAL
329. CONDICIONADOR MATIFICAÇÃO 400ML, HIGIENE PESSOAL
330. LÁPIS LABIAL 1UN, HIGIENE PESSOAL
331. BISCOITO RECHEADO OREO 130G, LANCHE
332. SALGADINHO ELMA CHIPS ORIGINAL 90G, LANCHE
333. BOLINHO DE CHUVA CONGELADO 300G, LANCHE
334. BOMBOM SONHO DE VALSA 110G, LANCHE
335. CHOCOLATE AO LEITE GAROTO 150G, LANCHE
336. ROSQUINHA DE COCO 200G, LANCHE
337. SALGADINHO SKINY ORIGINAL 60G, LANCHE
338. BISCOITO MAISENA PIRACANJUBA 400G, LANCHE
339. BOLACHA ÁGUA E SAL NESTLÉ 200G, LANCHE
340. TORTUGUITA SORTIDOS 134G, LANCHE
341. SALGADINHO ANELITOS CEBOLA 41G, LANCHE
342. BISCOITO DE POLVILHO YOKI 100G, LANCHE
343. BISCOITO WAFER CHOCOLATE 140G, LANCHE
344. BOMBOM ALPINO 85G, LANCHE
345. CHOCOLATE MEIO AMARGO 100G, LANCHE
346. SALGADINHO DE MILHO 100G, LANCHE
347. BISCOITO CREAM CRACKER 400G, LANCHE
348. PÃO DE MEL 200G, LANCHE
349. SALGADINHO BATATA PALHA 100G, LANCHE
350. BISCOITO DE CHOCOLATE 200G, LANCHE
351. BOMBOM DIAMENTE NEGRO 100G, LANCHE
352. CHOCOLATE BRANCO 100G, LANCHE
353. SALGADINHO CROCANTE 100G, LANCHE
354. BISCOITO RECHEADO MORANGO 130G, LANCHE
355. BEIJO DE MOÇA 200G, LANCHE
356. SALGADINHO TORCIDA 100G, LANCHE
357. BISCOITO SABOR LIMÃO 200G, LANCHE
358. OVOMALTINE 400G, LANCHE
359. SALGADINHO CHEETOS 100G, LANCHE
360. BISCOITO RECHEADO CHOCOLATE BRANCO 130G, LANCHE
361. PAÇOQUITA 200G, LANCHE
362. SALGADINHO DORITOS 100G, LANCHE
363. BISCOITO DE COCO 200G, LANCHE
364. CONFETTI 200G, LANCHE
365. SALGADINHO FANDANGOS 100G, LANCHE
366. BISCOITO RECHEADO GOIABADA 130G, LANCHE
367. SERENATA DE AMOR 200G, LANCHE
368. SALGADINHO PIPER 100G, LANCHE
369. BISCOITO SABOR MILHO 200G, LANCHE
370. CHOCOLATE COM AMENDOIM 100G, LANCHE
371. SALGADINHO BACON 100G, LANCHE
372. BISCOITO RECHEADO PRESTÍGIO 130G, LANCHE
373. CHOKITO 50G, LANCHE
374. SALGADINHO QUEIJO 100G, LANCHE
375. BISCOITO DE LEITE 200G, LANCHE
376. SORTIDOS DE CHOCOLATE 200G, LANCHE
377. SALGADINHO PRESUNTO E QUEIJO 100G, LANCHE
378. BISCOITO RECHADO CLUBE SOCIAL 288G, LANCHE
379. SURPRESA DE PÁSCOA 100G, LANCHE
380. SALGADINHO CALABRESA 100G, LANCHE
381. BISCOITO DE AVEIA 200G, LANCHE
382. AMENDOIM JAPONÊS 100G, LANCHE
383. SALGADINHO FRANGO 100G, LANCHE
384. BISCOITO RECHEADO NEGRO 130G, LANCHE
385. TABLETE DE CHOCOLATE 30G, LANCHE
386. SALGADINHO CARNE DE SOL 100G, LANCHE
387. BISCOITO SABOR MEL 200G, LANCHE
388. BARRA DE CEREAL 30G, LANCHE
389. SALGADINHO PIZZA 100G, LANCHE
390. BISCOITO INTEGRAL 200G, LANCHE
391. GOMA DE MASCAR 7UN, LANCHE
392. SALGADINHO ERVILHA 100G, LANCHE
393. BISCOITO RECHEADO MARACUJÁ 130G, LANCHE
394. PIPOCA DE MICROONDAS 100G, LANCHE
395. SALGADINHO TOMATE SEC 100G, LANCHE
396. BISCOITO DE MILHO VERDE 200G, LANCHE
397. BALA SORTIDA 100G, LANCHE
398. SALGADINHO CATUPIRY 100G, LANCHE
399. BISCOITO RECHEADO CHOC MENTA 130G, LANCHE
400. GOIABADA CASCÃO 200G, LANCHE
401. SALGADINHO KARITOS 40G, LANCHE
402. BISCOITO DE BANANA 200G, LANCHE
403. BOMBOM CROCANTE 100G, LANCHE
404. SALGADINHO CEBOLINHA 100G, LANCHE
405. BISCOITO RECHEADO TRUFADO 130G, LANCHE
406. TORTUGUINHA 50G, LANCHE
407. SALGADINHO CHURRASCO 100G, LANCHE
408. BISCOITO SABOR ABACAXI 200G, LANCHE
409. CHOCOLATE DIET 100G, LANCHE
410. SALGADINHO SALSICHA 100G, LANCHE
411. BISCOITO DE GENGIBRE 200G, LANCHE
412. BOMBOM AO LICOR 100G, LANCHE
413. SALGADINHO VINAGRETE 100G, LANCHE
414. BISCOITO RECHEADO FLOCOS 130G, LANCHE
415. TRUFA DE CHOCOLATE 100G, LANCHE
416. SALGADINHO PIMENTA 100G, LANCHE
417. BISCOITO DE POLVILHO AZEDO 100G, LANCHE
418. CHOCOLATE COM CASTANHA 100G, LANCHE
419. SALGADINHO ALCAPARRA 100G, LANCHE
420. BISCOITO RECHEADO BRIGADEIRO 130G, LANCHE
421. PALHA ITALIANA 100G, LANCHE
422. SALGADINHO CHEDDAR 100G, LANCHE
423. BISCOITO DE CENOURA 200G, LANCHE
424. OVOS DE PÁSCOA 100G, LANCHE
425. SALGADINHO TOMATE SECO 100G, LANCHE
426. BISCOITO RECHEADO LIMÃO 130G, LANCHE
427. AMENDOIM DOCE 100G, LANCHE
428. SALGADINHO RÚCULA 100G, LANCHE
429. BISCOITO DE BETERRABA 200G, LANCHE
430. CHOCOLATE COM FRUTAS VERMELHAS 100G, LANCHE
431. REFRIGERANTE COCA-COLA 2L, BEBIDAS
432. SUCO DEL VALE UVA 1L, BEBIDAS
433. ÁGUA MINERAL CRYSTAL 1.5L, BEBIDAS
434. CERVEJA SKOL 600ML, BEBIDAS
435. VINHO CHILENO 750ML, BEBIDAS
436. BEBIDA ENERGÉTICA RED BULL 250ML, BEBIDAS
437. CHÁ MATE LEÃO 1L, BEBIDAS
438. REFRIGERANTE GUARANÁ ANTARCTICA 2L, BEBIDAS
439. SUCO DE LARANJA 1L, BEBIDAS
440. ÁGUA COM GÁS 1.5L, BEBIDAS
441. CERVEJA ITAIPAVA 600ML, BEBIDAS
442. VINHO ARGENTINO 750ML, BEBIDAS
443. BEBIDA ENERGÉTICA MONSTER 473ML, BEBIDAS
444. CHÁ VERDE 1L, BEBIDAS
445. REFRIGERANTE FANTA LARANJA 2L, BEBIDAS
446. SUCO DE MARACUJÁ 1L, BEBIDAS
447. ÁGUA TÔNICA 1.5L, BEBIDAS
448. CERVEJA BRAHMA 600ML, BEBIDAS
449. VINHO NACIONAL 750ML, BEBIDAS
450. ISOTÔNICO GATORADE 500ML, BEBIDAS
451. CHÁ DE CAMOMILA 1L, BEBIDAS
452. REFRIGERANTE SPRITE 2L, BEBIDAS
453. SUCO DE MANGA 1L, BEBIDAS
454. ÁGUA DE COCO 1L, BEBIDAS
455. CERVEJA HEINEKEN 330ML, BEBIDAS
456. VINHO FRISANTE 750ML, BEBIDAS
457. BEBIDA ESPUMANTE 750ML, BEBIDAS
458. CHÁ PRETO 1L, BEBIDAS
459. REFRIGERANTE PEPSI 2L, BEBIDAS
460. SUCO DE PÊSSEGO 1L, BEBIDAS
461. ÁGUA SABOR LIMÃO 1.5L, BEBIDAS
462. CERVEJA ORIGINAL 330ML, BEBIDAS
463. VINHO ROSÉ 750ML, BEBIDAS
464. CALDO DE CANA 1L, BEBIDAS
465. CHÁ DE HORTELÃ 1L, BEBIDAS
466. REFRIGERANTE KUAT 2L, BEBIDAS
467. SUCO DE MORANGO 1L, BEBIDAS
468. ÁGUA MINERAL COM LIMÃO 1.5L, BEBIDAS
469. CERVEJA CORONA 330ML, BEBIDAS
470. VINHO PORTUGUÊS 750ML, BEBIDAS
471. SODA LIMÃO 1.5L, BEBIDAS
472. CHÁ BRANCO 1L, BEBIDAS
473. REFRIGERANTE SODA LIMÃO 2L, BEBIDAS
474. SUCO DE ABACAXI 1L, BEBIDAS
475. ÁGUA COM GÁS SABOR LARANJA 1.5L, BEBIDAS
476. CERVEJA BUDWEISER 330ML, BEBIDAS
477. VINHO TINTO 750ML, BEBIDAS
478. ÁGUA AROMATIZADA 1.5L, BEBIDAS
479. CHÁ GELADO 1L, BEBIDAS
480. REFRIGERANTE ANTARCTICA ZERO 2L, BEBIDAS
481. GARFO DE MESA TRAMONTINA 1UN, OUTROS
482. FACA DE COZINHA 1UN, OUTROS
483. COLHER DE SOPA 1UN, OUTROS
484. TÁBUA DE CORTE PLÁSTICA 1UN, OUTROS
485. PANELA DE PRESSÃO 4.5L, OUTROS
486. FRIGIDEIRA ANTIADERENTE 20CM, OUTROS
487. PRATO DE JANTAR 1UN, OUTROS
488. COPO DE VIDRO 300ML 1UN, OUTROS
489. PIREX REDONDO 20CM, OUTROS
490. ASSADEIRA DE ALUMÍNIO 1UN, OUTROS
491. PRENDEDOR DE CABELO 1UN, OUTROS
492. SANDÁLIA HAVAIANAS 1UN, OUTROS
493. LENÇO UMEDECIDO 1UN, OUTROS
494. VASSOURA 1UN, OUTROS
495. RODO 1UN, OUTROS
496. BALDE 10L, OUTROS
497. PANO DE PRATO 1UN, OUTROS
498. ESCOVA DE LIMPEZA 1UN, OUTROS
499. LÂMPADA LED 1UN, OUTROS
500. PILHA AA 4UN, OUTROS
"""

    linhas = produtos_texto.strip().split("\n")
    produtos = []

    for linha in linhas:
        linha = linha.strip()
        if not linha:
            continue

        # Remove "n. " do início, ex: "1. ARROZ..."
        if ". " in linha:
            parte_num, resto = linha.split(". ", 1)
            if parte_num.isdigit():
                linha = resto

        # Separa nome e categoria pela última vírgula
        if ", " in linha:
            nome_original, categoria = linha.rsplit(", ", 1)
            produtos.append((nome_original.strip(), categoria.strip()))

    return produtos


# -----------------------------------------------------------------------------
# Função principal: popular banco
# -----------------------------------------------------------------------------
def popular_banco():
    """Limpa as tabelas e insere os 500 produtos com histórico de preços fictícios."""
    conn = conectar()
    cursor = conn.cursor()

    # Limpar tabelas
    print("🧹 Limpando tabelas existentes (historico_precos, produtos)...")
    cursor.execute("DELETE FROM historico_precos;")
    cursor.execute("DELETE FROM produtos;")
    conn.commit()

    produtos = processar_lista_produtos()
    total_produtos = len(produtos)

    print(f"📦 Processando {total_produtos} produtos...")
    print("=" * 60)

    inseridos = 0
    categorias_processadas: dict[str, int] = {}

    precos_por_categoria = {
        "ALIMENTOS BÁSICOS": (5.0, 50.0),
        "HORTIFRUTI": (2.0, 20.0),
        "LATICÍNIOS": (3.0, 30.0),
        "LIMPEZA": (5.0, 60.0),
        "HIGIENE PESSOAL": (2.0, 40.0),
        "LANCHE": (1.0, 25.0),
        "BEBIDAS": (3.0, 40.0),
        "OUTROS": (2.0, 100.0),
    }

    mercados_ficticios = [
        "ATACADAO DIA A DIA",
        "CARREFOUR",
        "EXTRA",
        "PAO DE ACUCAR",
        "MERCADO LOCAL",
    ]

    data_base = datetime.now()

    for i, (nome_original, categoria_desejada) in enumerate(produtos, start=1):
        try:
            # Gera um "ean" estável a partir do nome
            ean = hashlib.md5(nome_original.encode("utf-8")).hexdigest()[:12]

            marca = extrair_marca(nome_original)
            unidade = determinar_unidade(nome_original)
            nome_limpo = gerar_nome_limpo(nome_original, marca)

            categoria = categoria_desejada.upper()

            # Insere produto
            cursor.execute(
                """
                INSERT INTO produtos (ean, nome_original, nome_limpo, marca, categoria, unidade)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (ean) DO NOTHING;
            """,
                (ean, nome_original, nome_limpo, marca, categoria, unidade),
            )

            categorias_processadas[categoria] = categorias_processadas.get(categoria, 0) + 1

            # Preço fictício pela categoria
            preco_min, preco_max = precos_por_categoria.get(categoria, (5.0, 50.0))
            preco = round(random.uniform(preco_min, preco_max), 2)

            # Quantidade fictícia
            if unidade in {"kg", "l"}:
                quantidade = round(random.uniform(0.5, 5.0), 2)
            elif unidade in {"g", "ml"}:
                quantidade = round(random.uniform(100, 1000), 0)
            else:
                quantidade = random.randint(1, 10)

            # Data aleatória nos últimos 30 dias
            dias_atras = random.randint(0, 30)
            data_compra = (data_base - timedelta(days=dias_atras)).strftime("%Y-%m-%d")

            mercado = random.choice(mercados_ficticios)

            cursor.execute(
                """
                INSERT INTO historico_precos (ean, data_compra, mercado, preco_pago, quantidade)
                VALUES (%s, %s, %s, %s, %s);
            """,
                (ean, data_compra, mercado, preco, quantidade),
            )

            inseridos += 1

            if i % 50 == 0:
                print(f"✅ Processados {i}/{total_produtos} produtos...")

        except Exception as e:
            print(
                f"❌ Erro ao processar produto {i}: {nome_original[:50]}... "
                f"- {str(e)[:80]}"
            )
            conn.rollback()

    conn.commit()
    cursor.close()
    conn.close()

    print("\n" + "=" * 60)
    print("📊 RELATÓRIO DE INSERÇÃO")
    print("=" * 60)
    print(f"✅ Total de produtos processados: {total_produtos}")
    print(f"✅ Registros inseridos (historico_precos): {inseridos}")
    print(f"✅ Categorias encontradas: {len(categorias_processadas)}")

    print("\n📈 Distribuição por categoria:")
    for categoria, qtd in sorted(categorias_processadas.items()):
        print(f"  • {categoria:20}: {qtd:3} produtos")

    return inseridos


# -----------------------------------------------------------------------------
# Execução direta
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("🎯 POPULANDO BANCO DE DADOS COM PRODUTOS DE TREINAMENTO")
    print("=" * 60)

    criar_tabelas_se_nao_existirem()
    total_inseridos = popular_banco()

    print("\n" + "=" * 60)
    print(f"✨ Processo concluído! {total_inseridos} produtos foram inseridos.")
    print("=" * 60)
    print("\n📝 Próximos passos sugeridos:")
    print("1. python ver_relatorio_nuvem.py")
    print("2. python ver_relatorio_categorias.py (se já existir)")
    print("3. Testar a IA com novas notas usando: python ia_groq_utils.py")
